Website/Controllers/ImagesController.cs
using System.Linq;
using System.Web.Mvc;
using HPlusSports.Models;

namespace HPlusSports.Controllers
{
    public class ImagesController : Controller
    {
        private readonly HPlusSportsDbContext _context;

        public ImagesController()
            : this(new HPlusSportsDbContext())
        {
        }

        public ImagesController(HPlusSportsDbContext context)
        {
            _context = context;
        }

        // /images/category/{SKU}
        // Redirects to the main image for a category
        public ActionResult Category(string id)
        {
            var imageId =
                _context.Categories
                    .Where(x => x.Key == id)
                    .Select(x => x.ImageId)
                    .FirstOrDefault();

            return Image(imageId);
        }

        // /images/product/{SKU}
        // Redirects to the main image for a product
        public ActionResult Product(string id)
        {
            var imageId =
                _context.Products
                    .Where(x => x.SKU == id)
                    .SelectMany(x => x.Images.Select(img => img.Id))
                    .FirstOrDefault();

            return Image(imageId);
        }

        public ActionResult Image(long? id)
        {
            var image = _context.Images.FirstOrDefault(x => x.Id == id);

            if (!string.IsNullOrWhiteSpace(image.Url))
            {
                return RedirectPermanent(image.Url);
            }

            if (image?.Content == null)
            {
                image = GetPlaceholderImage();
            }

            return File(image.Content, image.ContentType);
        }


        internal static volatile byte[] PlaceholderImageContent;

        private Image GetPlaceholderImage()
        {
            if (PlaceholderImageContent == null)
            {
                var path = Server.MapPath("~/Content/placeholder.jpg");
                PlaceholderImageContent = System.IO.File.ReadAllBytes(path);
            }

            return new Image
            {
                Content = PlaceholderImageContent,
                ContentType = "image/jpeg"
            };
        }
    }
}

Website/Controllers/InventoryController.cs
using HPlusSports.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace HPlusSports.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class InventoryController : Controller
    {
        private HPlusSportsDbContext _context;

        public InventoryController()
          : this(new HPlusSportsDbContext())
        {
        }

        public InventoryController(HPlusSportsDbContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            var products =
              _context.Products
                .OrderBy(x => x.Category.Name)
                .ThenBy(x => x.Name);

            return View(products);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            product.LastUpdated = DateTime.UtcNow;
            product.LastUpdatedUserId = GetUserId(this);

            _context.Products.Add(product);
            _context.SaveChanges();

            TempData["SuccessMessage"] =
              $"Successfully created \"{product.Name}\"";

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Update(long id)
        {
            var existing = _context.Products.Find(id);

            if (existing == null)
            {
                return ProductListError(
                  $"Couldn't update product #\"{id}\": product not found!"
                );
            }

            return View(existing);
        }

        [HttpPost]
        public ActionResult Update(long id, Product product)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var existing = _context.Products.Find(id);

            if (existing == null)
            {
                return ProductListError(
                  $"Couldn't update product #\"{id}\": product not found!"
                );
            }

            var hasPriceChanged = existing.Price != product.Price;

            existing.CategoryId = product.CategoryId;
            existing.Description = product.Description;
            existing.MSRP = product.MSRP;
            existing.Name = product.Name;
            existing.Price = product.Price;
            existing.SKU = product.SKU;
            existing.Summary = product.Summary;

            existing.LastUpdated = DateTime.UtcNow;
            existing.LastUpdatedUserId = GetUserId(this);

            _context.SaveChanges();

            if (hasPriceChanged)
            {
                var cartsToUpdate =
                  _context.ShoppingCarts
                    .Include("Items")
                    .Where(cart => cart.Items.Any(x => x.SKU == product.SKU));

                foreach (var cart in cartsToUpdate)
                {
                    foreach (var cartItem in cart.Items.Where(x => x.SKU == product.SKU))
                    {
                        cartItem.Price = product.Price;
                    }

                    cart.Recalculate();
                }
            }

            _context.SaveChanges();

            TempData["SuccessMessage"] =
              $"Successfully updated \"{product.Name}\"";

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(long id)
        {
            var product = _context.Products.Find(id);

            if (product == null)
            {
                return ProductListError(
                  $"Couldn't delete \"{product.Name}\": product not found!"
                );
            }

            _context.Products.Remove(product);
            _context.SaveChanges();

            TempData["SuccessMessage"] =
              $"Successfully deleted \"{product.Name}\"";

            return RedirectToAction(nameof(Index));
        }

        private ActionResult ProductListError(string error)
        {
            TempData["ErrorMessage"] = error;
            return RedirectToAction(nameof(Index));
        }

        protected override void OnResultExecuting(ResultExecutingContext filterContext)
        {
            ViewData["CategoryId"] =
              _context.Categories
                  .Select(x => new SelectListItem
                  {
                      Text = x.Name,
                      Value = x.Id.ToString(),
                  })
                  .ToArray();
        }

        // Overwriteable function for unit testing
        internal Func<Controller, string> GetUserId =
            (controller) => controller.User.Identity.Name;
    }
}

Website/Controllers/ProductsController.cs
using System.Linq;
using System.Web.Mvc;
using HPlusSports.Models;

namespace HPlusSports.Controllers
{
    public class ProductsController : Controller
    {
        public const int DefaultPageSize = 8;

        private readonly HPlusSportsDbContext _context;

        public ProductsController()
            : this(new HPlusSportsDbContext())
        {
        }

        public ProductsController(HPlusSportsDbContext context)
        {
            _context = context;
        }

        public ActionResult Index(int? page = null, int? count = null)
        {
            return Category(null, page, count);
        }

        public ActionResult Category(string id, int? page = null, int? count = null)
        {
            var category = _context.Categories.FirstOrDefault(x => x.Key == id);

            IQueryable<Product> products = _context.Products;

            if (category == null)
            {
                products =
                  products
                    .OrderBy(x => x.CategoryId)
                    .ThenBy(x => x.Name);
            }
            else
            {
                products =
                  products
                    .Where(x => x.CategoryId == category.Id)
                    .OrderBy(x => x.Name);
            }

            var skus = products.Select(x => x.SKU);
            var ratings = _context.GetProductRatings(skus);

            ViewData["Ratings"] = ratings;
            ViewData["Category"] = category ?? new Category { Name = "All Categories" };

            /**** Paging Logic ****/
            var model = products;
            var resultsCount = model.Count();
            var pageSize = count.GetValueOrDefault(DefaultPageSize);
            var currentPage = page.GetValueOrDefault(1);
            var pageCount = resultsCount / pageSize + (resultsCount % pageSize > 0 ? 1 : 0);
            var previousPage = (currentPage - 1 > 0) ? currentPage - 1 : (int?)null;
            var nextPage = (currentPage + 1 <= pageCount) ? currentPage + 1 : (int?)null;

            model = model
              .Skip((currentPage - 1) * pageSize)
              .Take(pageSize);

            ViewData["PageSize"] = pageSize;
            ViewData["ResultsCount"] = resultsCount;
            ViewData["CurrentPage"] = currentPage;
            ViewData["PageCount"] = pageCount;
            ViewData["PreviousPage"] = previousPage;
            ViewData["NextPage"] = nextPage;

            /**** End Paging Logic ****/

            return View("ProductList", model);
        }

        public ActionResult Product(string id)
        {
            var product = _context.FindProductBySku(id);

            if (product == null)
                return HttpNotFound();

            var imageIds =
                product
                  .Images
                    .Select(img => img.Id)
                    .ToArray();

            ViewData["Rating"] = _context.GetProductRating(product.SKU);
            ViewData["Category"] = product.Category;
            ViewData["Images"] = imageIds;

            return View(product);
        }
    }
}

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - H+ Sport</title>
  <link rel="dns-prefetch" href="//fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
  @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")
  <link rel="icon" href="https://hplussport.com/wp-content/uploads/2015/12/cropped-HSport_01-32x32.png" sizes="32x32">
</head>
<body>
  <div class="navbar">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="~/" class="navbar-brand">
          <img src="~/Content/logo.png" />
        </a>
      </div>
      <div class="col-md-7 text-center title navbar-header">
        <h1>@ViewData["Title"]</h1>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <li class="dropdown">
            @if (User.IsInRole(HPlusSports.Models.UserRoles.Admin))
            {
                <a class="dropbtn" href="@Url.Action("Index", "Inventory")">
                  <i class="glyphicon glyphicon-list-alt"></i>
                  Inventory
                </a>
            }
          </li>
          <li class="dropdown">
            @{
                var cart = HPlusSports.Application.Cart;
            }
            <a class="dropbtn nav-cart">
              <i class="glyphicon glyphicon-shopping-cart"></i>
              Cart
              @if (cart.Items.Any())
              {
                  <span>
                    (@cart.Items.Count() items)
                  </span>
              }
            </a>
            <div class="dropdown-content">

              @if (cart.Items.Count == 0)
              {
                  <p>Your shopping cart is empty - keep shopping!</p>
              }
              else
              {
                  <table class="table table-condensed">
                    @foreach (var item in cart.Items)
                    {
                        <tr class="text-middle">
                          <td>
                            <a href="@Url.Action("Remove", "Cart", new { id = item.Id })">
                              <i class="glyphicon glyphicon-remove text-danger"></i>
                            </a>
                          </td>
                          <td>
                            <img width="50" height="50" src="@Url.Action("Product", "Images", new { id = item.SKU })" alt="">
                          </td>
                          <td>
                            <a href="@Url.Action("Product", "Products", new { id = item.SKU })">
                              @item.Name
                            </a>
                          </td>
                          <td class="text-right">
                            @item.Quantity
                            x
                            @item.Price.ToString("C")
                          </td>
                        </tr>
                    }
                    <tr>
                      <th colspan="3" class="text-right">
                        Subtotal:
                      </th>
                      <th class="text-right">
                        @cart.Subtotal.ToString("C")
                      </th>
                    </tr>
                  </table>
              }

              <p class="buttons text-right" ">
                <a href="@Url.Action("Index", "Cart")" class="btn btn-default">View Cart</a>
              </p>
            </div>
          </li>
          <li>
            @if (User.Identity.IsAuthenticated)
            {
                <form method="post" action="@Url.Action("Logoff", "Account", new { area = "" })">
                  @Html.AntiForgeryToken()
                  <button type="submit" class="btn btn-default">Logout</button>
                </form>
            }
            else
            {
                <div>
                  <a href="@Url.Action("Login", "Account")" class="btn btn-default">Login</a>
                </div>
            }
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div id="main" class="container">
    @RenderBody()
  </div>

  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/bootstrap")
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.30.1/js/jquery.tablesorter.min.js"></script>
  @Scripts.Render("~/bundles/site")
  @RenderSection("scripts", required: false)
</body>
</html>